//! C source projection, not the compiler backend boundary.

use std::collections::BTreeSet;

use anyhow::{Result, anyhow, bail};
use serde_json::Value as JsonValue;

use crate::expr::{op_precedence, unary_precedence};
use crate::model::{ProgramRootPayload, param_names, preferred_names};
use crate::store::CodeDb;
use crate::types::type_hash_for;

impl CodeDb {
    pub(crate) fn render_c(&self, root_hash: &str) -> Result<String> {
        let root = self.load_root(root_hash)?;
        ensure_unique_c_projection_symbols(&root)?;
        let mut out = String::new();
        out.push_str("/* generated by codedb: no allocation, no managed runtime */\n\n");
        for binding in preferred_names(&root) {
            let entry = self
                .root_symbol(&root, &binding.symbol)
                .ok_or_else(|| anyhow!("root name points to missing symbol {}", binding.symbol))?;
            let c_symbol_name = self.c_symbol_name_for_symbol(&root, &binding.symbol)?;
            out.push_str(&format!(
                "{} {}({});\n",
                self.c_return_type(&entry.signature)?,
                c_symbol_name,
                self.c_param_list(&root, &binding.symbol, &entry.signature)?
            ));
        }
        out.push('\n');
        for binding in preferred_names(&root) {
            let entry = self
                .root_symbol(&root, &binding.symbol)
                .ok_or_else(|| anyhow!("root name points to missing symbol {}", binding.symbol))?;
            if self.definition_is_external(&entry.definition)? {
                continue;
            }
            let body = self.function_body_hash(&entry.definition)?;
            let params = param_names(&root, &binding.symbol);
            out.push_str(&format!(
                "{} {}({}) {{\n",
                self.c_return_type(&entry.signature)?,
                c_symbol_name_for_binding(&binding.module, &binding.display_name),
                self.c_param_list(&root, &binding.symbol, &entry.signature)?
            ));
            let return_type = self.signature_parts(&entry.signature)?.1;
            if return_type == type_hash_for("Unit") {
                out.push_str(&format!(
                    "    {};\n",
                    self.c_expr(&body, &root, &params, 0)?
                ));
                out.push_str("    return;\n");
            } else {
                out.push_str(&format!(
                    "    return {};\n",
                    self.c_expr(&body, &root, &params, 0)?
                ));
            }
            out.push_str("}\n\n");
        }
        ensure_no_forbidden_runtime_calls(&out)?;
        Ok(out)
    }

    pub(crate) fn c_return_type(&self, signature_hash: &str) -> Result<&'static str> {
        let (_, return_type) = self.signature_parts(signature_hash)?;
        self.c_type(&return_type)
    }

    pub(crate) fn c_type(&self, type_hash: &str) -> Result<&'static str> {
        let type_name = self.type_name(type_hash)?;
        match type_name.as_str() {
            "i64" => Ok("long"),
            "bool" => Ok("int"),
            "unit" => Ok("void"),
            _ => bail!("C projection v0 does not support aggregate type {type_name}"),
        }
    }

    pub(crate) fn c_param_list(
        &self,
        root: &ProgramRootPayload,
        symbol: &str,
        signature_hash: &str,
    ) -> Result<String> {
        let (params, _) = self.signature_parts(signature_hash)?;
        if params.is_empty() {
            return Ok("void".to_string());
        }
        let names = param_names(root, symbol);
        let mut c_names = BTreeSet::new();
        params
            .iter()
            .enumerate()
            .map(|(idx, ty)| {
                let name = c_identifier(names.get(idx).map(String::as_str).unwrap_or("p"));
                if !c_names.insert(name.clone()) {
                    bail!("C projection parameter name collision for symbol {symbol}: {name}");
                }
                Ok(format!("{} {}", self.c_type(ty)?, name))
            })
            .collect::<Result<Vec<_>>>()
            .map(|items| items.join(", "))
    }

    pub(crate) fn c_expr(
        &self,
        expr_hash: &str,
        root: &ProgramRootPayload,
        local_params: &[String],
        parent_prec: u8,
    ) -> Result<String> {
        self.c_expr_with_locals(expr_hash, root, local_params, &mut Vec::new(), parent_prec)
    }

    fn c_expr_with_locals(
        &self,
        expr_hash: &str,
        root: &ProgramRootPayload,
        local_params: &[String],
        locals: &mut Vec<CBinding>,
        parent_prec: u8,
    ) -> Result<String> {
        let payload = self.get_payload(expr_hash)?;
        let rendered = match payload
            .get("expr_kind")
            .and_then(JsonValue::as_str)
            .ok_or_else(|| anyhow!("expression missing expr_kind {expr_hash}"))?
        {
            "literal_i64" => payload
                .get("value")
                .and_then(JsonValue::as_str)
                .ok_or_else(|| anyhow!("literal_i64 missing value"))?
                .to_string(),
            "literal_bool" => {
                if payload
                    .get("value")
                    .and_then(JsonValue::as_bool)
                    .ok_or_else(|| anyhow!("literal_bool missing value"))?
                {
                    "1".to_string()
                } else {
                    "0".to_string()
                }
            }
            "literal_unit" => "((void)0)".to_string(),
            "param_ref" => {
                let index = payload
                    .get("index")
                    .and_then(JsonValue::as_u64)
                    .ok_or_else(|| anyhow!("param_ref missing index"))?
                    as usize;
                c_identifier(local_params.get(index).map(String::as_str).unwrap_or("p"))
            }
            "local_ref" => {
                let depth = payload
                    .get("depth")
                    .and_then(JsonValue::as_u64)
                    .ok_or_else(|| anyhow!("local_ref missing depth"))?
                    as usize;
                let binding = c_local_at_depth(locals, depth)
                    .ok_or_else(|| anyhow!("local_ref depth out of bounds: {depth}"))?;
                if binding.type_hash == type_hash_for("Unit") {
                    "((void)0)".to_string()
                } else {
                    binding.c_name.clone()
                }
            }
            "call" => {
                let symbol = payload
                    .get("symbol")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("call missing symbol"))?;
                let args = payload
                    .get("args")
                    .and_then(JsonValue::as_array)
                    .ok_or_else(|| anyhow!("call missing args"))?;
                let rendered_args = args
                    .iter()
                    .map(|arg| {
                        let hash = arg
                            .as_str()
                            .ok_or_else(|| anyhow!("call arg must be hash"))?;
                        self.c_expr_with_locals(hash, root, local_params, locals, 0)
                    })
                    .collect::<Result<Vec<_>>>()?;
                format!(
                    "{}({})",
                    self.c_symbol_name_for_symbol(root, symbol)?,
                    rendered_args.join(", ")
                )
            }
            "binary" => {
                let op = payload
                    .get("op")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("binary missing op"))?;
                let left = payload
                    .get("left")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("binary missing left"))?;
                let right = payload
                    .get("right")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("binary missing right"))?;
                let prec = op_precedence(op);
                let expr = format!(
                    "{} {} {}",
                    self.c_expr_with_locals(left, root, local_params, locals, prec)?,
                    c_binary_operator(op),
                    self.c_expr_with_locals(right, root, local_params, locals, prec + 1)?
                );
                if prec < parent_prec {
                    format!("({expr})")
                } else {
                    expr
                }
            }
            "unary" => {
                let op = payload
                    .get("op")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("unary missing op"))?;
                let child = payload
                    .get("expr")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("unary missing expr"))?;
                let prec = unary_precedence();
                let expr = format!(
                    "{op}{}",
                    self.c_expr_with_locals(child, root, local_params, locals, prec)?
                );
                if prec < parent_prec {
                    format!("({expr})")
                } else {
                    expr
                }
            }
            "let" => {
                let name = payload
                    .get("binding_name")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("let missing binding_name"))?;
                let binding_type = payload
                    .get("binding_type")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("let missing binding_type"))?;
                let value_hash = payload
                    .get("value")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("let missing value"))?;
                let body_hash = payload
                    .get("body")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("let missing body"))?;
                let value = self.c_expr_with_locals(value_hash, root, local_params, locals, 0)?;
                let c_name = c_identifier(name);
                locals.push(CBinding {
                    c_name: c_name.clone(),
                    type_hash: binding_type.to_string(),
                });
                let body = self.c_expr_with_locals(body_hash, root, local_params, locals, 0);
                locals.pop();
                let body = body?;
                if binding_type == type_hash_for("Unit") {
                    format!("({{ {value}; {body}; }})")
                } else {
                    format!(
                        "({{ {} {c_name} = {value}; {body}; }})",
                        self.c_type(binding_type)?
                    )
                }
            }
            "if" => {
                let cond = payload
                    .get("cond")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("if missing cond"))?;
                let then_hash = payload
                    .get("then")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("if missing then"))?;
                let else_hash = payload
                    .get("else")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("if missing else"))?;
                format!(
                    "({} ? {} : {})",
                    self.c_expr_with_locals(cond, root, local_params, locals, 0)?,
                    self.c_expr_with_locals(then_hash, root, local_params, locals, 0)?,
                    self.c_expr_with_locals(else_hash, root, local_params, locals, 0)?
                )
            }
            "borrow_shared" | "borrow_mut" | "slice_from_array" | "slice_len" | "subslice"
            | "assign" | "record_literal" | "field_access" | "enum_construct" | "case" | "fold"
            | "array_literal" | "array_fill" | "array_set" | "array_index" | "return" => {
                bail!(
                    "C projection v0 does not support {other}",
                    other = payload
                        .get("expr_kind")
                        .and_then(JsonValue::as_str)
                        .unwrap_or("aggregate expression")
                )
            }
            other => bail!("unknown expression kind {other}"),
        };
        Ok(rendered)
    }

    fn c_symbol_name_for_symbol(&self, root: &ProgramRootPayload, symbol: &str) -> Result<String> {
        let entry = self
            .root_symbol(root, symbol)
            .ok_or_else(|| anyhow!("symbol missing from root {symbol}"))?;
        if self.definition_is_external(&entry.definition)? {
            return Ok(self
                .external_function_metadata(&entry.definition)?
                .link_name);
        }
        let binding = self
            .preferred_binding(root, symbol)
            .ok_or_else(|| anyhow!("symbol has no display name {symbol}"))?;
        Ok(c_symbol_name_for_binding(
            &binding.module,
            &binding.display_name,
        ))
    }
}

#[derive(Debug, Clone)]
struct CBinding {
    c_name: String,
    type_hash: String,
}

fn ensure_unique_c_projection_symbols(root: &ProgramRootPayload) -> Result<()> {
    let mut names = BTreeSet::new();
    for binding in preferred_names(root) {
        let c_name = c_symbol_name_for_binding(&binding.module, &binding.display_name);
        if !names.insert(c_name.clone()) {
            bail!(
                "C projection symbol collision after identifier normalization: {}",
                c_name
            );
        }
    }
    Ok(())
}

fn c_symbol_name(display_name: &str) -> String {
    format!("codedb_{}", c_identifier(display_name))
}

fn c_symbol_name_for_binding(module: &str, display_name: &str) -> String {
    if module == "main" {
        c_symbol_name(display_name)
    } else {
        format!(
            "codedb_{}_{}",
            c_identifier(module),
            c_identifier(display_name)
        )
    }
}

fn c_identifier(name: &str) -> String {
    let mut out = String::new();
    for (idx, ch) in name.chars().enumerate() {
        if ch == '_' || ch.is_ascii_alphanumeric() {
            if idx == 0 && ch.is_ascii_digit() {
                out.push('_');
            }
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() { "_".to_string() } else { out }
}

fn c_binary_operator(op: &str) -> &str {
    match op {
        "&&" => "&",
        "||" => "|",
        other => other,
    }
}

pub(crate) fn ensure_no_forbidden_runtime_calls(source: &str) -> Result<()> {
    let bytes = source.as_bytes();
    let mut idx = 0;
    while idx < bytes.len() {
        if is_c_ident_start(bytes[idx]) {
            let start = idx;
            idx += 1;
            while idx < bytes.len() && is_c_ident_continue(bytes[idx]) {
                idx += 1;
            }
            let ident = &source[start..idx];
            let mut next = idx;
            while next < bytes.len() && bytes[next].is_ascii_whitespace() {
                next += 1;
            }
            if next < bytes.len() && bytes[next] == b'(' && forbidden_runtime_ident(ident) {
                bail!("forbidden_runtime_dependency: generated C calls {ident}");
            }
        } else {
            idx += 1;
        }
    }
    Ok(())
}

fn forbidden_runtime_ident(ident: &str) -> bool {
    matches!(ident, "malloc" | "free" | "printf" | "dlopen")
        || ident.starts_with("pthread_")
        || ident.starts_with("GC_")
}

fn is_c_ident_start(byte: u8) -> bool {
    byte == b'_' || byte.is_ascii_alphabetic()
}

fn is_c_ident_continue(byte: u8) -> bool {
    byte == b'_' || byte.is_ascii_alphanumeric()
}

fn c_local_at_depth(locals: &[CBinding], depth: usize) -> Option<&CBinding> {
    locals
        .len()
        .checked_sub(depth + 1)
        .and_then(|idx| locals.get(idx))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn runtime_check_detects_calls_not_generated_identifier_substrings() {
        ensure_no_forbidden_runtime_calls("long codedb_free(void) { return 1; }\n").unwrap();
        assert!(ensure_no_forbidden_runtime_calls("void f(void) { free(); }\n").is_err());
        assert!(ensure_no_forbidden_runtime_calls("void f(void) { pthread_create(); }\n").is_err());
    }
}
