//! C source projection, not the compiler backend boundary.

use anyhow::{Result, anyhow, bail};
use serde_json::Value as JsonValue;

use crate::expr::op_precedence;
use crate::model::{ProgramRootPayload, param_names, preferred_names};
use crate::store::CodeDb;
use crate::types::type_hash_for;

impl CodeDb {
    pub(crate) fn render_c(&self, root_hash: &str) -> Result<String> {
        let root = self.load_root(root_hash)?;
        let mut out = String::new();
        out.push_str("/* generated by codedb: no allocation, no managed runtime */\n\n");
        for binding in preferred_names(&root) {
            let entry = self
                .root_symbol(&root, &binding.symbol)
                .ok_or_else(|| anyhow!("root name points to missing symbol {}", binding.symbol))?;
            out.push_str(&format!(
                "{} {}({});\n",
                self.c_return_type(&entry.signature)?,
                c_symbol_name(&binding.display_name),
                self.c_param_list(&root, &binding.symbol, &entry.signature)?
            ));
        }
        out.push('\n');
        for binding in preferred_names(&root) {
            let entry = self
                .root_symbol(&root, &binding.symbol)
                .ok_or_else(|| anyhow!("root name points to missing symbol {}", binding.symbol))?;
            let body = self.function_body_hash(&entry.definition)?;
            let params = param_names(&root, &binding.symbol);
            out.push_str(&format!(
                "{} {}({}) {{\n",
                self.c_return_type(&entry.signature)?,
                c_symbol_name(&binding.display_name),
                self.c_param_list(&root, &binding.symbol, &entry.signature)?
            ));
            let return_type = self.signature_parts(&entry.signature)?.1;
            if return_type == type_hash_for("Unit") {
                out.push_str("    return;\n");
            } else {
                out.push_str(&format!(
                    "    return {};\n",
                    self.c_expr(&body, &root, &params, 0)?
                ));
            }
            out.push_str("}\n\n");
        }
        ensure_no_forbidden_runtime_calls(&out)?;
        Ok(out)
    }

    pub(crate) fn c_return_type(&self, signature_hash: &str) -> Result<&'static str> {
        let (_, return_type) = self.signature_parts(signature_hash)?;
        self.c_type(&return_type)
    }

    pub(crate) fn c_type(&self, type_hash: &str) -> Result<&'static str> {
        match self.type_name(type_hash)? {
            "i64" => Ok("long"),
            "bool" => Ok("int"),
            "unit" => Ok("void"),
            _ => unreachable!(),
        }
    }

    pub(crate) fn c_param_list(
        &self,
        root: &ProgramRootPayload,
        symbol: &str,
        signature_hash: &str,
    ) -> Result<String> {
        let (params, _) = self.signature_parts(signature_hash)?;
        if params.is_empty() {
            return Ok("void".to_string());
        }
        let names = param_names(root, symbol);
        params
            .iter()
            .enumerate()
            .map(|(idx, ty)| {
                Ok(format!(
                    "{} {}",
                    self.c_type(ty)?,
                    c_identifier(names.get(idx).map(String::as_str).unwrap_or("p"))
                ))
            })
            .collect::<Result<Vec<_>>>()
            .map(|items| items.join(", "))
    }

    pub(crate) fn c_expr(
        &self,
        expr_hash: &str,
        root: &ProgramRootPayload,
        local_params: &[String],
        parent_prec: u8,
    ) -> Result<String> {
        let payload = self.get_payload(expr_hash)?;
        let rendered = match payload
            .get("expr_kind")
            .and_then(JsonValue::as_str)
            .ok_or_else(|| anyhow!("expression missing expr_kind {expr_hash}"))?
        {
            "literal_i64" => payload
                .get("value")
                .and_then(JsonValue::as_str)
                .ok_or_else(|| anyhow!("literal_i64 missing value"))?
                .to_string(),
            "literal_bool" => {
                if payload
                    .get("value")
                    .and_then(JsonValue::as_bool)
                    .ok_or_else(|| anyhow!("literal_bool missing value"))?
                {
                    "1".to_string()
                } else {
                    "0".to_string()
                }
            }
            "param_ref" => {
                let index = payload
                    .get("index")
                    .and_then(JsonValue::as_u64)
                    .ok_or_else(|| anyhow!("param_ref missing index"))?
                    as usize;
                c_identifier(local_params.get(index).map(String::as_str).unwrap_or("p"))
            }
            "call" => {
                let symbol = payload
                    .get("symbol")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("call missing symbol"))?;
                let args = payload
                    .get("args")
                    .and_then(JsonValue::as_array)
                    .ok_or_else(|| anyhow!("call missing args"))?;
                let rendered_args = args
                    .iter()
                    .map(|arg| {
                        let hash = arg
                            .as_str()
                            .ok_or_else(|| anyhow!("call arg must be hash"))?;
                        self.c_expr(hash, root, local_params, 0)
                    })
                    .collect::<Result<Vec<_>>>()?;
                format!(
                    "{}({})",
                    c_symbol_name(&self.symbol_display(root, symbol)?),
                    rendered_args.join(", ")
                )
            }
            "binary" => {
                let op = payload
                    .get("op")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("binary missing op"))?;
                let left = payload
                    .get("left")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("binary missing left"))?;
                let right = payload
                    .get("right")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("binary missing right"))?;
                let prec = op_precedence(op);
                let expr = format!(
                    "{} {} {}",
                    self.c_expr(left, root, local_params, prec)?,
                    op,
                    self.c_expr(right, root, local_params, prec + 1)?
                );
                if prec < parent_prec {
                    format!("({expr})")
                } else {
                    expr
                }
            }
            "if" => {
                let cond = payload
                    .get("cond")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("if missing cond"))?;
                let then_hash = payload
                    .get("then")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("if missing then"))?;
                let else_hash = payload
                    .get("else")
                    .and_then(JsonValue::as_str)
                    .ok_or_else(|| anyhow!("if missing else"))?;
                format!(
                    "({} ? {} : {})",
                    self.c_expr(cond, root, local_params, 0)?,
                    self.c_expr(then_hash, root, local_params, 0)?,
                    self.c_expr(else_hash, root, local_params, 0)?
                )
            }
            other => bail!("unknown expression kind {other}"),
        };
        Ok(rendered)
    }
}

fn c_symbol_name(display_name: &str) -> String {
    format!("codedb_{}", c_identifier(display_name))
}

fn c_identifier(name: &str) -> String {
    let mut out = String::new();
    for (idx, ch) in name.chars().enumerate() {
        if ch == '_' || ch.is_ascii_alphanumeric() {
            if idx == 0 && ch.is_ascii_digit() {
                out.push('_');
            }
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() { "_".to_string() } else { out }
}

pub(crate) fn ensure_no_forbidden_runtime_calls(source: &str) -> Result<()> {
    for forbidden in ["malloc", "free", "printf", "pthread_", "GC_", "dlopen"] {
        if source.contains(forbidden) {
            bail!("forbidden_runtime_dependency: generated C contains {forbidden}");
        }
    }
    Ok(())
}
